#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Markus Hilger <admin@obihoernchen.net>
# @copyright Copyright (c) 2009-2015 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_COLLECTD_CONFIG=${OMV_COLLECTD_CONFIG:-"/etc/collectd/collectd.conf"}
OMV_COLLECTD_RRDTOOL_MKGRAPH=${OMV_COLLECTD_RRDTOOL_MKGRAPH:-"/usr/sbin/omv-mkgraph"}

cat <<EOF >> ${OMV_COLLECTD_CONFIG}
LoadPlugin exec
<Plugin exec>
        Exec "nobody" "/usr/local/bin/cpufanspeed"
</Plugin>

EOF

cat <<EOF >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
# Plugin: cpufanspeed
TITLE_CPUFANSPEED="CPU fan speed"
COLOR_CANVAS="#ffffff"               # white
COLOR_CPUFANSPEED="#ff0000"          # red
COLOR_CPUFANSPEED_TRANS="#ff000044"  # red
EOF
for ucperiod in HOUR DAY WEEK MONTH YEAR; do
        lcperiod=$(echo ${ucperiod} | tr '[:upper:]' '[:lower:]')
        cat <<EOF >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
rrdtool graph \${IMGDIR}/cpufanspeed-${lcperiod}.png --start \${${ucperiod}START} \${DEFAULTS} --title "\${TITLE_CPUFANSPEED}\${${ucperiod}TITLE}" --slope-mode --upper-limit 100 --lower-limit 0 --rigid --vertical-label Percent \
  DEF:cpufanspeed_max=\${DATA}/fanspeed/fanspeed.rrd:value:MAX \
  AREA:cpufanspeed_max\${COLOR_CPUFANSPEED_TRANS} \
  AREA:cpufanspeed_min\${COLOR_CANVAS} \
  LINE1:cpufanspeed_avg\${COLOR_CPUFANSPEED}:"Speed" \
  GPRINT:cpufanspeed_min:MIN:"%5.1lf%s Min" \
  GPRINT:cpufanspeed_avg:AVERAGE:"%5.1lf%s Avg" \
  GPRINT:cpufanspeed_max:MAX:"%5.1lf%s Max" \
  GPRINT:cpufanspeed_avg:LAST:"%5.1lf%s Last\l" \
  COMMENT:"\${LASTUPDATE}" >/dev/null
EOF
done
